# Generated by Django 5.2.8 on 2025-11-15 01:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(help_text='로또 회차 번호', unique=True, verbose_name='회차')),
                ('draw_date', models.DateField(verbose_name='추첨일')),
                ('num1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('num2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('num3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('num4', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('num5', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('num6', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('bonus_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')], verbose_name='보너스 번호')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lotto.lottoround', verbose_name='회차')),
                ('total_sales', models.IntegerField(default=0, verbose_name='총 판매액 (장)')),
                ('total_winners', models.IntegerField(default=0, verbose_name='총 당첨자 수 (모든 등수)')),
                ('rank1_winners', models.IntegerField(default=0, verbose_name='1등 당첨자')),
                ('rank2_winners', models.IntegerField(default=0, verbose_name='2등 당첨자')),
                ('rank3_winners', models.IntegerField(default=0, verbose_name='3등 당첨자')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto_type', models.CharField(choices=[('A', '자동'), ('M', '수동')], default='M', max_length=1, verbose_name='구매 유형')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('p_num1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('p_num2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('p_num3', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('p_num4', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('p_num5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('p_num6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='로또 번호는 1보다 작을 수 없습니다.'), django.core.validators.MaxValueValidator(45, message='로또 번호는 45보다 클 수 없습니다.')])),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotto.lottoround', verbose_name='구매 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
