# Generated by Django 5.1.2 on 2025-11-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottoround',
            name='draw_date',
        ),
        migrations.AddField(
            model_name='lottoround',
            name='actual_draw_date',
            field=models.DateTimeField(blank=True, help_text='관리자가 추첨을 완료한 시점', null=True, verbose_name='실제 추첨 일시'),
        ),
    ]
